### ISSUE TITLE
[BUG] Prevent duplicate modules from being added across semesters

### ISSUE THREAD

**Issue by NatashaKSS** [nus-mtp/nus-oracle#136]
* When you click on CS1010 for Sem 1, then click on CS1010 again for Sem 2, for example, there is no check to see if a duplicate module had already been added.

* Modules that are already in the user's study plan are also still shown on search results, so that might be a may to restrict user entry on your side!

**Comment by bsweeyee** [comment]
Duplicate modules will be handled in Module Validity checking. Will be closing this issue since it is a future feature
