### ISSUE TITLE
Deleting a new study plan does not reset tab index to previous

### ISSUE THREAD

**Issue by NatashaKSS** [nus-mtp/nus-oracle#137]
* Low priority because this is only a matter of convenience for the user

* Ideally, we want the tab's index to be set to the previous tab (on the left) so that the user will be re-directed to the previous-made study plan immediately upon deleting the rightmost study plan. Currently, because React's setState method is asynchronous, we cannot change the state in time for the render somehow.

* Tried solutions: Passing a callback method to setState to try and force it execute a function asynchronously

* Possible solutions: Force setState to be synchronous somehow

**Comment by NatashaKSS** [comment]
* This bug actually turned out to be ok since by deleting a study plan, it's good for user to see a blank screen so that they know that their "Delete" study plan command was successful

**Comment by walrys** [comment]
cheaterbug
