### ISSUE TITLE
Add link to JC/Polys waived + exempted list of mods

### ISSUE THREAD

**Issue by NatashaKSS** [nus-mtp/nus-oracle#211]
* Where to add this? Unsure, maybe somewhere near the waived/exempted modules cards on the Sidebar

* Because JCs need to refer to the NUS Computing website to check what modules are waived for them
* Because the many different polys have different modules that students are exempted from
* We might not be able to do JC/Poly check to find out the user's exempted/waived modules at acadSetup page due to project time constraints, so this is a workaround that at least makes adding exempted/waived modules more convenient for user

**Comment by walrys** [comment]
Added a tooltip at the component to include an external link and some information!
