### ISSUE TITLE
[AddStudyPlan] Create New Plan appears temporarily when user hasn't loaded all study plans yet

### ISSUE THREAD

**Issue by NatashaKSS** [nus-mtp/nus-oracle#292]
* Reproduce the bug by refreshing the page and stare at the study plan dashboard to see the "AddStudyPlan" component appear then disappear once all user study plans have been loaded.

* NOTE: Minor bug, no fret, other bugs more important!

**Comment by walrys** [comment]
Not a UI issue, bug is due to the time taken to download study plan on the client side.
When no study plan is present (or when they are still being loaded), the TabbedContainer will display none, and the Add New Study Plan dialog will be visible by default

**Comment by walrys** [comment]
To resolve this, we need to know when the user data is loading/fully loaded onto client's browser

**Comment by NatashaKSS** [comment]
Not a UI issue actually. Thanks @walrys !
