### ISSUE TITLE
[Modal] Error if you press ESC to close the window

### ISSUE THREAD

**Issue by NatashaKSS** [nus-mtp/nus-oracle#301]
* ESC keypress is the React library's event, not sure why this error is thrown...possibly something to do with the lifecycle methods.    

**ERROR MESSAGE:** Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ModalContainer component.

**Comment by walrys** [comment]
error was due to event listener for resizing window not being removed properly
