### ISSUE TITLE
[Modal] Styles for tabs become transparent upon closing modal for adding new study plan

### ISSUE THREAD

**Issue by walrys** [nus-mtp/nus-oracle#304]

**Comment by NatashaKSS** [comment]
Trying to reproduce this bug but it seems like it doesn't always happen (on the heroku dev branch, I didn't get any issue), not sure why, so need to observe again

**Comment by NatashaKSS** [comment]
This doesn't happen when you hide/close the <ModalContainer /> for "delete" study plan though.

**Comment by NatashaKSS** [comment]
I found that when you turn the "background" field of 
```
.tabs-section-nav .nav-item {
    float: left;
    background: #f6f8fa;
    white-space: nowrap;
}
```
on and then off again (in Chrome's "inspect element"), the bgcolor comes back to normal.
