### ISSUE TITLE
Bug: Create custom email account

### ISSUE THREAD

**Issue by tharain** [nus-mtp/nus-oracle#315]
When creating account with `youremail@custom.com, ..., @u.nus.edu` adding a comma between the emails can send a confirmation email to your customized email.
![2](https://cloud.githubusercontent.com/assets/12406584/24329391/14d39a4a-1238-11e7-9618-e3a72205ba41.png)

**Comment by NatashaKSS** [comment]
Thanks for the bug report!!!

Fixed by @IamVacer at commit f84ef2b
