### ISSUE TITLE
[Logout button] Should not be placed as a Tab but as a button under User Profile

### ISSUE THREAD

**Issue by NatashaKSS** [nus-mtp/nus-oracle#322]
* Prevents accidental clicks that initiate the entire logout process
* Removing Logout Tab from the sidebar makes the Tabs more logical. This is because clicking the other 2 buttons (User Profile and Requirements) brings up their respective panels but Logout will log the user out of the system entirely. Hence, these 2 buttons + Logout button are not very logically grouped which may confuse first-time users too

**Comment by walrys** [comment]
closed with d5ff420
